In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.datasets import load_breast_cancer, load_iris, load_digits

In [3]:
X, y = load_digits(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [46]:
lgr = LogisticRegression(solver='sag')
dt = DecisionTreeClassifier()

lgr.fit(X_train, y_train)
dt.fit(X_train, y_train)

y_pred_lgr = lgr.predict(X_test)
y_pred_dt = dt.predict(X_test)

/home/ree/python_venv/ML/lib64/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [47]:
print('Accuracy Score')
print(f'Logistic Regression : {accuracy_score(y_test, y_pred_lgr)}')
print(f'Decision Tree : {accuracy_score(y_test, y_pred_dt)}')

Accuracy Score
Logistic Regression : 0.9694444444444444
Decision Tree : 0.8527777777777777

In [48]:
pd.DataFrame(confusion_matrix(y_test, y_pred_lgr), columns=range(10))

    0   1   2   3   4   5   6   7   8   9
0  33   0   0   0   0   0   0   0   0   0
1   0  28   0   0   0   0   0   0   0   0
2   0   0  33   0   0   0   0   0   0   0
3   0   0   0  33   0   1   0   0   0   0
4   0   1   0   0  44   0   1   0   0   0
5   0   0   1   0   0  44   1   0   0   1
6   0   0   0   0   0   1  34   0   0   0
7   0   0   0   0   0   0   0  33   0   1
8   0   0   0   0   0   1   0   0  29   0
9   0   0   0   1   0   0   0   0   1  38

In [49]:
pd.DataFrame(confusion_matrix(y_test, y_pred_dt), range(10))

    0   1   2   3   4   5   6   7   8   9
0  29   0   0   0   2   1   0   1   0   0
1   0  22   1   0   1   0   0   1   2   1
2   0   0  27   3   1   0   0   1   1   0
3   0   0   0  31   0   0   0   0   2   1
4   0   0   0   0  42   1   1   1   1   0
5   1   0   0   1   1  39   1   0   0   4
6   1   0   0   0   1   1  32   0   0   0
7   0   0   0   2   1   0   0  31   0   0
8   0   2   0   1   1   1   0   1  22   2
9   0   0   0   3   1   0   0   4   0  32

In [50]:
accuracy_lgr = accuracy_score(y_test, y_pred_lgr)
precision_lgr = precision_score(y_test, y_pred_lgr, average='macro')
recall_lgr = recall_score(y_test, y_pred_lgr, average='macro')
f1_lgr = f1_score(y_test, y_pred_lgr, average='macro')
                 
accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt, average='macro')
recall_dt = recall_score(y_test, y_pred_dt, average='macro')
f1_dt = f1_score(y_test, y_pred_dt, average='macro')

metrics = pd.DataFrame({'Logistic Regression' : [accuracy_lgr, precision_lgr, recall_lgr, f1_lgr],
              'Decision Tree' : [accuracy_dt, precision_dt, recall_dt, f1_dt]})

metrics.index = ['Accuracy Score', 'Precision Score', 'Recall Score', 'F1 Score']

metrics

                 Logistic Regression  Decision Tree
Accuracy Score              0.969444       0.852778
Precision Score             0.970398       0.860493
Recall Score                0.972196       0.849666
F1 Score                    0.971155       0.852096

In [51]:
precision_lgr, recall_lgr, f1_lgr

(np.float64(0.9703975035844614),
 np.float64(0.9721963660579865),
 np.float64(0.9711554765459978))

In [52]:
precision_dt, recall_dt, f1_dt

(np.float64(0.8604930725149005),
 np.float64(0.8496663154371159),
 np.float64(0.8520957221946892))

In [68]:
precision_score(y_test, y_pred_lgr, average='macro')

np.float64(0.9703975035844614)

In [61]:
from sklearn.metrics import classification_report

print9(classification_report(y_test, y_pred_lgr))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        33
           1       0.97      1.00      0.98        28
           2       0.97      1.00      0.99        33
           3       0.97      0.97      0.97        34
           4       1.00      0.96      0.98        46
           5       0.94      0.94      0.94        47
           6       0.94      0.97      0.96        35
           7       1.00      0.97      0.99        34
           8       0.97      0.97      0.97        30
           9       0.95      0.95      0.95        40

    accuracy                           0.97       360
   macro avg       0.97      0.97      0.97       360
weighted avg       0.97      0.97      0.97       360